version: '3'
services:
    nginx:
        image: nginx:1.10.3
        container_name: oryxtc-nginx
        restart: always
        ports:
        - 80:80
        - 443:443
        links:
        - php7:php7_server
        volumes:
        - ./nginx:/etc/nginx/conf.d  #nginx配置文件目录
        - /etc/letsencrypt/live:/etc/letsencrypt/live  #certbot密钥文件夹
        - oryxtc-volume:/home/www
    php7:
        build:
            context: ./php7
        image: oryxtc/oryxtc-php7
        container_name: oryxtc-php7
        restart: always
        links:
        - mysql:mysql_server
        - redis:redis_server
        volumes:
        - oryxtc-volume:/home/www
    mysql:
        image: mysql:8.0
        container_name: oryxtc-mysql
        restart: always
        ports:
        - 3306:3306
        environment:
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
        volumes:
            - mysql-data:/var/lib/mysql
            - ./secrets/mysql-root:/run/secrets/mysql-root
    redis:
        build:
            context: ./redis
        image: oryxtc/oryxtc-redis
        container_name: oryxtc-redis
        restart: always
        ports:
        - 6379:6379
volumes:
    mysql-data:
    oryxtc-volume:
        driver: local-persist
        driver_opts:
            mountpoint: /home/www