version: '3'
services:
    nginx:
        image: nginx:1.10.3
        container_name: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - frontend
        volumes:
            - ./nginx:/etc/nginx/conf.d  #nginx配置文件目录
            - /etc/letsencrypt/:/etc/letsencrypt/  #certbot密钥文件夹
            - /home/www:/home/www
    php7:
        build:
            context: ./php7
        image: oryxtc/php7
        container_name: php7
        restart: always
        networks:
            frontend:
                aliases:
                    - php7_server
            backend:
                aliases:
                    - php7_server
        volumes:
           - ./php7/php.ini:/usr/local/etc/php/php.ini  #php配置文件目录
           - /home/www:/home/www
    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root
        networks:
            backend:
                aliases:
                    - mysql_server
        volumes:
            - mysql-data:/var/lib/mysql
            - ./secrets/mysql-root:/run/secrets/mysql-root
    redis:
        build:
            context: ./redis
        image: oryxtc/redis
        container_name: redis
        restart: always
        ports:
            - 6379:6379
networks:
    frontend:
    backend:
volumes:
    mysql-data: